### PR TITLE
US70_Bota

### PR DESCRIPTION
**Pull request by Akbota1991**

### CODE REVIEW

**Review by Munisa2 — CHANGES_REQUESTED** [review]
Sorry You have to many conflicts in
===> ("BrowserUtil, Hooks, BasePage, Driver, and CuckesRunner")

**Review by latifetor — CHANGES_REQUESTED** [review]
There are some conflict has to be edited: BasePage, Driver, Hooks, CukesRunner, BrowserUtils.

**Comment by ekilic76** [comment]
problem

**Review by Biljana523 — DISMISSED** [review]

**Comment by erkine** [comment]
x

**Pull request closed without merging**
